### PR TITLE
Inform user about lack of Mac support

### PR DESCRIPTION
**Pull request by SevenBits**
This pull request informs the user that unetbootin does not work on Mac, and directs the user to Mac Linux USB Loader, as discussed with @gkovacs.

### CODE REVIEW

**Comment by gkovacs** [comment]
You should probably only show the message directing the user to Mac Linux USB Loader if the user is on mac os x. As the windows and linux users (who account for the vast majority of users who visit the page) can't use your utility. This can be accomplished with some browser user agent checking in javascript (check to see if OSX is in the user agent string).

**Comment by gkovacs** [comment]
second note. index_template.html is the one you should be changing (index.html is generated by running upload.rb - it includes direct links to latest download versions)

**Comment by SevenBits** [comment]
@gkovacs Please review the latest changes.

**Comment by SevenBits** [comment]
@gkovacs Do you need to regenerate the `index.html` file?

**Comment by gkovacs** [comment]
already did it for you don't worry

**Comment by SevenBits** [comment]
Very nice, thank you. Noticed that you changed some of the HTML...

**Comment by gkovacs** [comment]
yeah seemed a tad bit deceptive to have the same type of "download" button if it was for a different piece of software and didn't actually download it. figured it would lead to less confusion. also the most common distributions (ubuntu, mint, fedora) all bundle UEFI loaders on their CDs now so the unetbootin-generated USBs do work, so it's only for the less-common distributions that it's necessary for users to switch to your tool

**Comment by SevenBits** [comment]
Seems okay. The only thing is that if they're on a Mac without JavaScript enabled the message won't appear.

**Pull request merged**
